import bread from '~/assets/svg/bread.svg';
import eggplant from '~/assets/svg/eggplant.svg';
import fruit from '~/assets/svg/fruit.svg';
import grill from '~/assets/svg/grill.svg';
import international from '~/assets/svg/international.svg';
import kid from '~/assets/svg/kid.svg';
import leave from '~/assets/svg/leave.svg';
import mortairAndPestle from '~/assets/svg/mortair-and-pestle.svg';
import mug from '~/assets/svg/mug.svg';
import pan from '~/assets/svg/pan.svg';
import pickles from '~/assets/svg/pickles.svg';
import pot from '~/assets/svg/pot.svg';
import potWithCross from '~/assets/svg/pot-with-cross.svg';
import { NavMenuItem } from '~/types/nav-menu';

export const NAV_MENU_ITEMS: NavMenuItem[] = [
    {
        category: 'Салаты',
        path: '/salads',
        imgSrc: eggplant,
        subCategories: [
            { category: 'Мясные салаты', path: '/meat' },
            { category: 'Рыбные салаты', path: '/fish' },
            { category: 'Овощные салаты', path: '/vegetable' },
            { category: 'Теплые салаты', path: '/warm' },
        ],
    },
    {
        category: 'Закуски',
        path: '/snacks',
        imgSrc: fruit,
        subCategories: [
            { category: 'Мясные закуски', path: '/meat' },
            { category: 'Рыбные закуски', path: '/fish' },
            { category: 'Овощные закуски', path: '/vegetable' },
            { category: 'Теплые закуски', path: '/warm' },
            { category: 'Бутерброды', path: '/sandwiches' },
            { category: 'Фастфуд', path: '/fast-food' },
        ],
    },
    {
        category: 'Первые блюда',
        path: '/first',
        imgSrc: pot,
        subCategories: [
            { category: 'Мясные супы', path: '/meat' },
            { category: 'Овощные супы', path: '/vegetable' },
            { category: 'Бульоны', path: '/broths' },
            { category: 'Холодные супы', path: '/cold' },
            { category: 'Диетические супы', path: '/diet' },
        ],
    },
    {
        category: 'Вторые блюда',
        path: '/second',
        imgSrc: pan,
        subCategories: [
            { category: 'Мясные', path: '/meat' },
            { category: 'Рыбные', path: '/fish' },
            { category: 'Овощные', path: '/vegetable' },
            { category: 'Из птицы', path: '/poultry' },
            { category: 'Из грибов', path: '/mushroom' },
            { category: 'Из субпродуктов', path: '/sub-products' },
            { category: 'На пару', path: '/steamed' },
            { category: 'Пельмени, вареники', path: '/dumplings' },
            { category: 'Мучные гарниры', path: '/flour' },
            { category: 'Овощные гарниры', path: '/vegetable' },
            { category: 'Пицца', path: '/pizza' },
            { category: 'Суши', path: '/sushi' },
        ],
    },
    {
        category: 'Десерты и выпечка',
        path: '/desserts',
        imgSrc: bread,
        subCategories: [
            { category: 'Блины и оладьи', path: '/pancakes' },
            { category: 'Пироги и пончики', path: '/pies-donuts' },
            { category: 'Торты', path: '/cakes' },
            { category: 'Рулеты', path: '/rolls' },
            { category: 'Кексы и маффины', path: '/cupcakes-muffins' },
            { category: 'Сырники и ватрушки', path: '/cheese-pancakes' },
            { category: 'Из слоеного теста', path: '/puff-pastry' },
            { category: 'Из заварного теста', path: '/choux-pastry' },
            { category: 'Из дрожжевого теста', path: '/yeast-dough' },
            { category: 'Булочки и сдоба', path: '/buns-pastries' },
            { category: 'Хлеб', path: '/bread' },
            { category: 'Тесто на пиццу', path: '/pizza-dough' },
            { category: 'Кремы', path: '/creams' },
        ],
    },
    {
        category: 'Блюда на гриле',
        path: '/grill',
        imgSrc: grill,
        subCategories: [
            { category: 'Говядина', path: '/beef' },
            { category: 'Свинина', path: '/pork' },
            { category: 'Птица', path: '/bird' },
            { category: 'Рыба', path: '/fish' },
            { category: 'Грибы', path: '/mushrooms' },
            { category: 'Овощи', path: '/vegetables' },
        ],
    },
    {
        category: 'Веганская кухня',
        path: '/vegan',
        imgSrc: leave,
        subCategories: [
            { category: 'Закуски', path: '/appetizers' },
            { category: 'Первые блюда', path: '/first' },
            { category: 'Вторые блюда', path: '/second' },
            { category: 'Гарниры', path: '/garnish' },
            { category: 'Десерты', path: '/desserts' },
            { category: 'Выпечка', path: '/bakery' },
            { category: 'Сыроедческие блюда', path: '/raw' },
            { category: 'Напитки', path: '/drinks' },
        ],
    },
    {
        category: 'Детские блюда',
        path: '/kid',
        imgSrc: kid,
        subCategories: [
            { category: 'Первые блюда', path: '/first' },
            { category: 'Вторые блюда', path: '/second' },
            { category: 'Гарниры', path: '/garnish' },
            { category: 'Выпечка', path: '/bakery' },
            { category: 'Без глютена', path: '/gluten-free' },
            { category: 'Без сахара', path: '/sugar-free' },
            { category: 'Без аллергенов', path: '/allergen-free' },
            { category: 'Блюда для прикорма', path: '/baby-food' },
        ],
    },
    {
        category: 'Лечебное питание',
        path: '/medical',
        imgSrc: potWithCross,
        subCategories: [
            { category: 'Детская диета', path: '/children-diet' },
            { category: 'Диета №1', path: '/diet-1' },
            { category: 'Диета №2', path: '/diet-2' },
            { category: 'Диета №3', path: '/diet-3' },
            { category: 'Диета №5', path: '/diet-5' },
            { category: 'Диета №6', path: '/diet-6' },
            { category: 'Диета №7', path: '/diet-7' },
            { category: 'Диета №8', path: '/diet-8' },
            { category: 'Диета №9', path: '/diet-9' },
            { category: 'Диета №10', path: '/diet-10' },
            { category: 'Диета №11', path: '/diet-11' },
            { category: 'Диета №12', path: '/diet-12' },
            { category: 'Диета №13', path: '/diet-13' },
            { category: 'Диета №14', path: '/diet-14' },
            { category: 'Без глютена', path: '/gluten-free' },
            { category: 'Без аллергенов', path: '/allergen-free' },
        ],
    },
    {
        category: 'Национальные',
        path: '/national',
        imgSrc: international,
        subCategories: [
            { category: 'Американская кухня', path: '/american' },
            { category: 'Армянская кухня', path: '/armenian' },
            { category: 'Греческая кухня', path: '/greek' },
            { category: 'Грузинская кухня', path: '/georgian' },
            { category: 'Итальянская кухня', path: '/italian' },
            { category: 'Испанская кухня', path: '/spanish' },
            { category: 'Китайская кухня', path: '/chinese' },
            { category: 'Мексиканская кухня', path: '/mexican' },
            { category: 'Паназиатская кухня', path: '/pan-asian' },
            { category: 'Русская кухня', path: '/russian' },
            { category: 'Турецкая кухня', path: '/turkish' },
            { category: 'Французская кухня', path: '/french' },
            { category: 'Шведская кухня', path: '/swedish' },
            { category: 'Японская кухня', path: '/japanese' },
            { category: 'Другая кухня', path: '/other' },
        ],
    },
    {
        category: 'Соусы',
        path: '/sauces',
        imgSrc: mortairAndPestle,
        subCategories: [
            { category: 'Соусы мясные', path: '/meat-sauces' },
            { category: 'Соусы сырные', path: '/cheese-sauces' },
            { category: 'Маринады', path: '/marinades' },
        ],
    },
    {
        category: 'Напитки',
        path: '/drinks',
        imgSrc: mug,
        subCategories: [
            { category: 'Соки и фреши', path: '/juices' },
            { category: 'Смузи', path: '/smoothies' },
            { category: 'Компоты', path: '/compotes' },
            { category: 'Кисели', path: '/jellies' },
            { category: 'Кофе', path: '/coffee' },
            { category: 'Лечебный чай', path: '/herbal-tea' },
            { category: 'Квас', path: '/kvass' },
            { category: 'Коктейли', path: '/cocktails' },
            { category: 'Алкогольные', path: '/alcohol' },
        ],
    },
    {
        category: 'Заготовки',
        path: '/pickled',
        imgSrc: pickles,
        subCategories: [
            { category: 'Мясные заготовки', path: '/meat' },
            { category: 'Рыбные заготовки', path: '/fish' },
            { category: 'Из огурцов', path: '/cucumber' },
            { category: 'Из томатов', path: '/tomato' },
            { category: 'Из грибов', path: '/mushroom' },
            { category: 'Овощные заготовки', path: '/vegetable' },
            { category: 'Салаты, икра', path: '/salads-caviar' },
            { category: 'Из фруктов и ягод', path: '/fruit-berry' },
        ],
    },
];
