export const PLACEHOLDERS = {
    search: 'Название или ингредиент...',
    selectFromList: 'Выберите из списка...',
    differentAllergen: 'Другой аллерген',
    searchByCategories: 'Поиск по категории',
    searchByAuthor: 'Поиск по автору',
    meatType: 'Тип мяса:',
    sidesType: 'Тип гарнира:',
    login: 'Введите логин',
    password: 'Пароль для сайта',
    name: 'Имя',
    lastName: 'Фамилия',
    email: 'e-mail',
    loginShort: 'Логин',
    passwordShort: 'Пароль',
    oldPassword: 'Старый пароль',
    newPassword: 'Новый пароль',
    repeatPassword: 'Повторите пароль',
    recipeTitle: 'Название рецепта',
    recipeDescription: 'Краткое описание рецепта',
    ingredient: 'Ингредиент',
    measureUnit: 'Единица измерения',
    step: 'Шаг',
    ingredientMeasure: '300',
    maxNoteLength: 'максимально 160 символов',
};
