export const PLACEHOLDERS = {
    search: 'Название или ингредиент...',
    differentAllergen: 'Другой аллерген',
    searchByCategories: 'Поиск по категории',
    searchByAuthor: 'Поиск по автору',
    meatType: 'Тип мяса:',
    sidesType: 'Тип гарнира:',
    login: 'Введите логин',
    password: 'Пароль для сайта',
    name: 'Имя',
    lastName: 'Фамилия',
    email: 'e-mail',
    loginShort: 'Логин',
    passwordShort: 'Пароль',
    repeatPassword: 'Повторите пароль',
};
