export enum AxiosPaths {
    BASE_URL = 'https://marathon-api.clevertec.ru',
    LOG_IN = '/auth/login',
    REGISTRATION = '/auth/registration',
    AUTH_GOOGLE = '/auth/google',
    CHECK_EMAIL = '/auth/check-email',
    CONFIRM_EMAIL = '/auth/confirm-email',
    FORGOT_PASS = '/confirm-email',
    CHANGE_PASSWORD = '/auth/change-password',
    FEEDBACK = '/feedback',
    TRAINING = '/training',
    TRAINING_LIST = '/catalogs/training-list',
    USER_ME = '/user/me',
    UPLOAD_IMAGE = '/upload-image',
    CHANGE_USER_INFO = '/user',
    TARIFF_LIST = '/catalogs/tariff-list',
    PAY_TARIFF = '/tariff',
}